"""fixed USER table lazy load added to User table

Revision ID: 6d200593ea64
Revises: d904d4a6547c
Create Date: 2024-11-18 03:07:46.504753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d200593ea64'
down_revision: Union[str, None] = 'd904d4a6547c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
