"""fixed USER table lazy load added to User table

Revision ID: 92339f54acdf
Revises: 6d200593ea64
Create Date: 2024-11-18 03:28:27.518584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92339f54acdf'
down_revision: Union[str, None] = '6d200593ea64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
