"""added farm name

Revision ID: b2c62a09bdf5
Revises: 90014ec4573b
Create Date: 2024-10-04 00:49:12.036396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c62a09bdf5'
down_revision: Union[str, None] = '90014ec4573b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('farm_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmers', 'farm_name')
    # ### end Alembic commands ###
