"""updated to_dict method in Farmer class

Revision ID: b67c67a19293
Revises: b2c62a09bdf5
Create Date: 2024-10-08 23:12:13.028496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67c67a19293'
down_revision: Union[str, None] = 'b2c62a09bdf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
